package mark.mapper;

import java.util.List;
import mark.entity.Balance;

public interface BalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Sat Sep 24 20:12:26 CST 2016
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Sat Sep 24 20:12:26 CST 2016
     */
    int insert(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Sat Sep 24 20:12:26 CST 2016
     */
    Balance selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Sat Sep 24 20:12:26 CST 2016
     */
    List<Balance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Sat Sep 24 20:12:26 CST 2016
     */
    int updateByPrimaryKey(Balance record);
}