package mark.mapper;

import java.util.List;
import mark.entity.Pay;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Sat Sep 24 14:30:02 CST 2016
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Sat Sep 24 14:30:02 CST 2016
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Sat Sep 24 14:30:02 CST 2016
     */
    Pay selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Sat Sep 24 14:30:02 CST 2016
     */
    List<Pay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Sat Sep 24 14:30:02 CST 2016
     */
    int updateByPrimaryKey(Pay record);
}