package mark.entity;

import java.util.Date;

public class Pay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.userid
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.username
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.amount
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_by
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_time
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.detail
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.userid
     *
     * @return the value of pay.userid
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.userid
     *
     * @param userid the value for pay.userid
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.username
     *
     * @return the value of pay.username
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.username
     *
     * @param username the value for pay.username
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.amount
     *
     * @return the value of pay.amount
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.amount
     *
     * @param amount the value for pay.amount
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_by
     *
     * @return the value of pay.update_by
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_by
     *
     * @param updateBy the value for pay.update_by
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_time
     *
     * @return the value of pay.update_time
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_time
     *
     * @param updateTime the value for pay.update_time
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.detail
     *
     * @return the value of pay.detail
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.detail
     *
     * @param detail the value for pay.detail
     *
     * @mbg.generated Sat Sep 24 13:47:34 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}